### PR TITLE
fix #2575: Loader may not load native lib correctly due to resource n…

### LINKED ISSUE #2575: Native resource loader should avoid loading the same resource path from other jars.
**What version of OR-Tools and what language are you using?**
Version: v9.0.
Language: Java

**What did you expect to see**

JVM could load ortools lib correctly.

**What did you see instead?**

The ortools lib could not be loaded correctly.

The current native resource Loader (for Java) firstly `getNativeResourceURI()` from the class path. However, it just locates the native lib via a resource path: Platform.RESOURCE_PREFIX + "/", for eg, darwin-x86-64/, or linux-x86-64.

It is possible that other jars has the same resource directory. In this case, the loader could not load the native lib sometimes.

### PR DESCRIPTION
**Pull request by xianyinxin**
…ame conflicting.

### CODE REVIEW

**Comment by xianyinxin** [comment]
@Mizux Could you pls take a look?

**Comment by xianyinxin** [comment]
@googlebot I signed it!

**Review by Mizux — APPROVED** [review]
LGTM, need to test...

**Comment by stradivari96** [comment]
Small reminder to change merge target to `master`

**Comment by xianyinxin** [comment]
@Mizux @stradivari96 I've changed the target branch to master, could you pls retrigger the ckecks if needed?

**Pull request merged**
