### PR TITLE
Support pairs with disjunctions in local search operators

### PR DESCRIPTION
**Pull request by matthewrj**
This PR adds support for pairs with disjunctions in MakePairActiveOperator, MakePairInactiveOperator, PairRelocateOperator, LightPairRelocateOperator, PairExchangeOperator, PairExchangeRelocateOperator and IndexPairSwapActiveOperator. The existing implementation does not support disjunctions and only considers the first alternative of each disjunction, with the changes in the PR, all alternatives are considered.

This has been tested against a number of real-world test cases and achieves significant solution quality improvements.

### CODE REVIEW

**Comment by matthewrj** [comment]
I am working on adding disjunction support to other operators also, I wast thinking I would go through the PR process with just these two first then follow up with an additional PR with the others.

**Comment by matthewrj** [comment]
I have added disjunction support to the remaining operators and included it in the PR.

**Comment by lperron** [comment]
Hi, Thanks for the contrib.
I will let Vincent review the code

**Comment by matthewrj** [comment]
Any updates on this?

**Comment by Mizux** [comment]
Hi,

Sorry for the delay...
Thanks for your contribution,  AFAIK an internal stuff was "inspired" by this but contains few 
improvements...

Since we have something more or less similar internally -> I'll cancel this PR in favor of our internal implementation...

note: I'll try to make an export ASAP !

**Comment by Mizux** [comment]
FYI have been open sourced by https://github.com/google/or-tools/commit/56aed766fcfff700b24e6bd447e0a6cde3c25564 ~5months ago.

**Pull request closed without merging**
