### PR TITLE
Added model loader interfaces and updated unit tests

### PR DESCRIPTION
**Pull request by mwpowellhtx**
@lperron Please find the PR ready to go. Thanks!

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
@lperron How's it going in your neck of the woods?

**Comment by jculpon** [comment]
<bug scrub> is there a reason that someone @google hasn't been able to merge this patch?

**Comment by lperron** [comment]
Because I disagreed with some of the code.
And now, I have removed the model loader completely from the CP solver. I was never complete, too cumbersome, and badly designed.

**Comment by jculpon** [comment]
Thanks for the update, @lperron

**Pull request closed without merging**
