### PR TITLE
Example of a Vehicle Routing Problem with Uninterruptible Breaks

### PR DESCRIPTION
**Pull request by pmateusz**
An example of the Vehicle Routing Problem with Time Windows and Breaks. All breaks are mandatory and must be performed without interruptions. Since breaks without interruptions are not available off-the-shelf a custom constraint is developed. A warning message is printed every time vehicle's break overlaps with a visit.

Workaround for the issue: #569

### CODE REVIEW

**Comment by pmateusz** [comment]
I have signed it!

**Comment by Mizux** [comment]
Hi,

It seems "break" feature has been fixed internally, so I hope for v6.9 to bump routing library to our current internal code...

BTW I still keep this PR "open" until break is updated and this PR become obsolete.

**Comment by pmateusz** [comment]
So it was a bug indeed. Thank you for confirmation! I am pleased that the work I did helped a little. It is of course always better to fix the root cause rather than rely on the workaround my PR provides. Feel free to close the PR once it is best.

**Comment by tomika** [comment]
Dear Mateusz,
I would like to know if it is really neccessary to add
solver()->AddConstraint(solver()->MakeIntervalVarRelation(current_interval, Solver::STARTS_AFTER_END, last_interval));
constraints?
Is it not a basic, already existing constaint in the whole routing calculation?
Thanks for your answer in advance.

**Pull request closed without merging**
