### PR TITLE
Use uintptr_t

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by lperron** [comment]
Actually, it breaks our build.

I must refuse it.

**Comment by andreas-schwab** [comment]
In which way??

**Comment by lperron** [comment]
Ambiguous cast on Mac.

Le lun. 6 juin 2022, 13:12, Andreas Schwab ***@***.***> a
écrit :

**Comment by andreas-schwab** [comment]
In which way??

**Pull request closed without merging**
