### PR TITLE
A* for shortest path

### PR DESCRIPTION
**Pull request by wolfv**
I have added an implementation for the A* algorithm. 

The implementation is very similar to the Dijkstra implementation (since Dijkstra is a specialization of A*).

The constructor of the A* shortest path takes another callback called `heuristic` that should return a heuristic cost estimate for the node.

### CODE REVIEW

**Comment by wolfv** [comment]
The corporate contributors license agreement for wolf.vollprecht@rapyuta-robotics.com is signed. Can one trigger the google bot to do another check?

Cheers,

Wolf

**Comment by wolfv** [comment]
I am the author.

2016-04-25 13:48 GMT+02:00 googlebot <notifications@github.com>:

**Comment by wolfv** [comment]
I did author the commits and I confirm that I am okay with the contribution :)

**Comment by lperron** [comment]
I merged it.

Thanks for the contribution.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-04-25 18:27 GMT+02:00 Wolf Vollprecht <notifications@github.com>:

**Pull request merged**
