### PR TITLE
Distribute mypy files

### PR DESCRIPTION
**Pull request by stradivari96**
Fix https://github.com/google/or-tools/issues/1547

The *.pyi files were created (https://github.com/google/or-tools/commit/e1b32efb5af2fc6b486ca98528ef3f985f3e4b44) but not added to the wheel, this PR modifies `setup.py` to include them.

### CODE REVIEW

**Comment by stradivari96** [comment]
Gentle ping.

PS: more context https://stackoverflow.com/questions/34571088/how-to-distribute-type-hints-to-pypi

**Comment by lperron** [comment]
I did not manage to make it work on all platforms.

**Comment by stradivari96** [comment]
Are you talking about the `protoc-gen-mypy` part? On which platforms?
I can take a look but a simple fix could be to just commit the generated .pyi files

**Comment by Mizux** [comment]
Does the ortools .pyi files shouldn't be part of the [typeshed](https://github.com/python/typeshed) repo instead (like [protobuf](https://github.com/python/typeshed/tree/master/third_party/2and3/google/protobuf)) ?

**Comment by stradivari96** [comment]
Didn't know about that repo, but I believe or-tools may be a bit too specific to be included there.
Your protos also tend to change each version with new parameters so keeping that in sync could be a bit hard.

**Comment by stradivari96** [comment]
Investigating a bit more, it might be easier to just copy/clone [the scripts](https://github.com/dropbox/mypy-protobuf/tree/master/python) and use the other method indicated on the [README](https://github.com/dropbox/mypy-protobuf#python-implementation).

> Alternately, you can explicitly provide the path:
> ```
> protoc --plugin=protoc-gen-mypy=path/to/protoc-gen-mypy --python_out=output/location --mypy_out=output/location
> ```
> On windows, provide the bat file:
> ```
> protoc --plugin=protoc-gen-mypy=path/to/protoc_gen_mypy.bat --python_out=output/location --mypy_out=output/location
> ```

That should make it work across platforms and you can avoid the `pip install` (the only requirement is `protobuf>=3.6.0`)

**Comment by stradivari96** [comment]
Closing this for now, will reopen when I can work on it

**Comment by stradivari96** [comment]
Hi! I created and uploaded a package called [ortools-stubs](https://pypi.org/project/ortools-stubs/) to pypi similar to https://github.com/numpy/numpy-stubs, following [PEP-561](https://www.python.org/dev/peps/pep-0561/).

This way, running `pip install ortools-stubs` downloads all the `*.pyi` files enabling autocompletion (at least in Pycharm) for every platform.

Links:
* https://pypi.org/project/ortools-stubs/
* https://github.com/stradivari96/ortools-stubs

Hit me up if you want me to transfer the ownership of the pypi package.

**Pull request closed without merging**
