### PR TITLE
fix typo (unless we're going French)

### PR DESCRIPTION
**Pull request by ChefYeum**

### CODE REVIEW

**Comment by ChefYeum** [comment]
@googlebot I signed it!

**Review by Mizux — APPROVED** [review]

**Comment by Mizux** [comment]
Our dev branch is master, I'll cherry pick it on master

**Comment by Mizux** [comment]
my bad, by suppressing this PR you branch disappear, so I didn't get a chance to cherry pick it -_-
So I redo it with more fixes...
BTW Thx !

**Comment by ChefYeum** [comment]
@Mizux No worries, seems like I deleted the branch too soon

**Pull request closed without merging**
