### PR TITLE
divide the total z by 100 to match fruits final results

### PR DESCRIPTION
**Pull request by 0xYasser**
result show as : 
```
z: 1505
x: [1, 0, 0, 2, 0, 1]
1 of mixed fruit : 2.15
2 of host wings : 3.55
1 of samples place : 5.8
```
the `z` should be divided by `100.0` to match the fruits price.

### CODE REVIEW

**Comment by 0xYasser** [comment]
I already signed!

**Comment by 0xYasser** [comment]
I signed it!

**Comment by 0xYasser** [comment]
I signed it!

**Comment by iYasser** [comment]
I signed it!

**Comment by iYasser** [comment]
I signed it! again

**Comment by Mizux** [comment]
according to your patch https://patch-diff.githubusercontent.com/raw/google/or-tools/pull/828.patch
You use this address for email Yasser A <yasser@Yassers-MacBook-Pro-2.local>.

Maybe you need to amend it to change this.
`git commit --amend --author="Author Name <email@address.com>"`

**Pull request merged**
