### PR TITLE
added example for cvrptw in python

### PR DESCRIPTION
**Pull request by lfiaschi**
Translate the C++ example for the cvrptw to Python

### CODE REVIEW

**Comment by neumarina** [comment]
hi,when I run this example,an error happened.
Traceback (most recent call last):
  File "my_projects/cvrptw_new_test.py", line 153, in <module>
    solve_it()
  File "my_projects/cvrptw_new_test.py", line 64, in solve_it
    parameters = pywrapcp.RoutingSearchParameters()
AttributeError: 'module' object has no attribute 'RoutingSearchParameters'
how can I do next?

**Comment by neumarina** [comment]
hi,when I run this example,an error happened.
Traceback (most recent call last):
  File "my_projects/cvrptw_new_test.py", line 153, in <module>
    solve_it()
  File "my_projects/cvrptw_new_test.py", line 64, in solve_it
    parameters = pywrapcp.RoutingSearchParameters()
AttributeError: 'module' object has no attribute 'RoutingSearchParameters'
how can I do next?

**Comment by mjfwest** [comment]
@neumarina you could try the following similar example already in master.

https://github.com/google/or-tools/blob/master/examples/python/cvrptw.py

**Comment by neumarina** [comment]
@mjfwest the same error happened when I run examples/python/cvrptw.py

the error as follows:

Traceback (most recent call last):
  File "examples/python/cvrptw.py", line 737, in <module>
    main()
  File "examples/python/cvrptw.py", line 628, in main
    glob_param = pywrapcp.RoutingParameters()
AttributeError: 'module' object has no attribute 'RoutingParameters'

**Comment by lperron** [comment]
Hi,

I have ported the example to the new API.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-05-09 7:23 GMT+02:00 neumarina <notifications@github.com>:

**Comment by neumarina** [comment]
@lperron oh,thanks very much. The new one can run successfully

**Comment by daruni** [comment]
@neumarina Hi, neumarina. U said that the new one can run successfully. Could u please tell me where can i download it? I had a difficulty in trying to install or-tools in Windows with python27/python34. So, your help would be highly appreciated.

**Pull request closed without merging**
