### PR TITLE
Improvements to cvrp_reload.py

### PR DESCRIPTION
**Pull request by robin-vjc**
- Fixed an issue where the wrong index could have been passed to the disjunction in different examples.
- Improved module documentation

### CODE REVIEW

**Review by Mizux — CHANGES_REQUESTED** [review]
Approve this PR but should be done on **master** branch (our development branch while stable is our release one)...

Sorry

**Comment by Mizux** [comment]
oups, I manage to rebase  your branch against master but need a new PR to change here -_-

**Comment by Mizux** [comment]
OK push by hand your branch on master...

```sh
git clone git@github.com:robin-vjc/or-tools.git
git checkout improve-cvrp-reload-example
git remote add google git@github.com:google/or-tools.git
git fetch --all
git rebase google/master 
git push google HEAD:master
```

**Comment by robin-vjc** [comment]
@Mizux sorry - I realized something was off when I started to receive a bunch of CI notifications. Will make a new PR to master.

**Comment by Mizux** [comment]
@robin-vjc no need a new PR I manage to push them on master...

**Pull request closed without merging**
