### PR TITLE
add swig bindings for shortestpaths.h

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
yes, i have signed the CLA

**Comment by lperron** [comment]
Hi, 

In the meantime I have changed the code from callbacks to std::function, as I really want to get rid of callbacks.
So you should include the swig code util/python/functions.swig and include that instead.

Sorry for the extra work.

**Comment by lperron** [comment]
I have rewritten the diff on my side using std::function.
I believe you can delete this merge request.

Thanks for the suggestion.

**Comment by wolfv** [comment]
Hey Laurent, 

well, thanks! Great to see this stuff "merged".

Have a good weekend,

Wolf

**Pull request closed without merging**
