### PR TITLE
Get rid of appscript/gflags dependencies

### PR DESCRIPTION
**Pull request by cjdrake**
I see that @orwant filed #63 a while ago, regarding Python3 support. This commit is a baby step in that direction.

I recently asked @gpshead and @craigcitro about paths towards Python3 compatibility for or-tools. Since both google-appscript and gflags are Python2 only, and difficult to change, they suggested the path of least resistance might be to just get rid of them.

Please let me know what you think, and I can start making more changes like this.

### CODE REVIEW

**Comment by lperron** [comment]
A few years ago, I ported or-tools to python3.
Using 2to3, everything went fine.

The blocking point was protobuf.

I need to check if protobuf 3.0.0 pre-release supports python3.

And we would like to keep gflags/google appcript in the code to simplify our python examples.

**Comment by craigcitro** [comment]
protobuf3 supports python3, which is good going forward. i think it's unlikely that we'll get new gflags and apputils versions out any time soon, but your call.

**Comment by cjdrake** [comment]
Cool, I'm glad we're all in agreement about porting to Python3.

The Python examples directory is an excellent resource for newcomers. Shouldn't we make it accessible to as many of them as possible, whether they are using Python 2 or 3?

Also, IMO, this kind of change actually makes this example *simpler*. Why? Because it gets rid of a dependency that very few people are familiar with, and replaces it with the de-facto standard argument parsing library from Python's standard library. Plus, it gets rid of whatever `app.run()` is implicitly doing behind the scenes, and replaces it with the more explicit system exit. As [pep20](https://www.python.org/dev/peps/pep-0020/) would say, "explicit is better than implicit.

**Comment by lperron** [comment]
Hi, 

finally, I agree.
I have pushed a full cleanup that removed all dependencies on google-apputils and gflags.

Thanks for the suggestion.

You can delete this pull request.

**Comment by cjdrake** [comment]
Done. Thanks :).

**Pull request closed without merging**
