### PR TITLE
Remove <p>.. code-block:: c++</p>

### PR DESCRIPTION
**Pull request by sadikkuzu**

### CODE REVIEW

**Comment by lperron** [comment]
This is generated code.
This PR will be overwritten.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 29 déc. 2020 à 19:00, google-cla[bot] <notifications@github.com> a
écrit :

**Comment by sadikkuzu** [comment]
@googlebot I signed it!

**Comment by Mizux** [comment]
As laurent said it is auto generated from the following source code:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/algorithms/knapsack_solver.h#L71-L117
using the script:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/makefiles/Makefile.doc.mk#L25

**Comment by Mizux** [comment]
I'll try to see if using `@code{.py}` will help pdoc3 to generate a better html...
ref: https://www.doxygen.nl/manual/commands.html#cmdcode

**Comment by Mizux** [comment]
Now code block have the correct tag but I didn't see any `.. highlight:: language` as suggested in https://stackoverflow.com/questions/46892227/how-do-i-insert-highlight-or-code-block-into-sphinx-style-docstrings

BTW I'll close this PR

**Pull request closed without merging**
