### PR TITLE
Rte dev xpress

### PR DESCRIPTION
**Pull request by klorel**
Hello,
This PR is a new trial to integrate the solver FICO XPRESS in or-tools.

Manuel

### CODE REVIEW

**Comment by klorel** [comment]
@googlebot I consent

**Comment by lperron** [comment]
Please clean up the files (docs)

**Comment by ErDumont** [comment]
@googlebot I consent.

**Comment by klorel** [comment]
I've just merge the master in tro rte-dev-xpress and set the PR to the master branch.
Do we need to update the documentation files ?

**Comment by lperron** [comment]
Such a mess.

I would have synchronized the branch with master, created new branch,
manually merged the diffs in this branch, and create a new PR from scratch.

The new PR has inherited all the contributors from the old PR.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 6 août 2019 à 07:51, Manuel Ruiz <notifications@github.com> a
écrit :

**Comment by klorel** [comment]
ok, new trial then!

**Pull request closed without merging**
