### PR TITLE
Build issue fixes

### PR DESCRIPTION
**Pull request by ambasta**
Attempts to address issues while building on OSx #406

### CODE REVIEW

**Comment by lperron** [comment]
So, no luck on mac. Still error line 87.
I build it on linux. It went fine and built all 4 dependencies locally + the libraries.

The library is twice as big as the one I build.
Do you add debug information to the files?

Thanks

**Comment by ambasta** [comment]
Not really.. since the dependencies are statically compiled when the system wide libs aren't available, libortool links against them statically!

Also, line 87 now reads     SET(SUBTARGETS "")

Has the error message changed or are you still reflecting the old error?

**Comment by lperron** [comment]
I removed cbc from brew.
Now, cmake works fine.

Linking fails. It misses zlib and gflags (from what I can see in the log):

Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      ___cxx_global_var_init.20 in lp_solver.cc.o
      ___cxx_global_var_init.27 in lp_solver.cc.o
      ___cxx_global_var_init.6 in boolean_problem.cc.o
      ___cxx_global_var_init.5 in drat.cc.o
      ___cxx_global_var_init.17 in constraint_solver.cc.o
      ___cxx_global_var_init.26 in constraint_solver.cc.o
      ___cxx_global_var_init.68 in routing_flags.cc.o
      ...
  "google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)", referenced from:
      ___cxx_global_var_init in time_limit.cc.o
      ___cxx_global_var_init.3 in mps_reader.cc.o
      ___cxx_global_var_init.6 in mps_reader.cc.o
      ___cxx_global_var_init.3 in lp_solver.cc.o
      ___cxx_global_var_init.6 in lp_solver.cc.o
      ___cxx_global_var_init.9 in lp_solver.cc.o
      ___cxx_global_var_init.12 in lp_solver.cc.o
      ...
  "google::FlagRegisterer::FlagRegisterer<double>(char const*, char const*, char const*, double*, double*)", referenced from:
      ___cxx_global_var_init in routing.cc.o
      ___cxx_global_var_init.45 in routing_flags.cc.o
      ___cxx_global_var_init.76 in routing_flags.cc.o
  "google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)", referenced from:
      ___cxx_global_var_init in bitset.cc.o
      ___cxx_global_var_init.15 in lp_solver.cc.o
      ___cxx_global_var_init.3 in linear_assignment.cc.o
      ___cxx_global_var_init in shortestpaths.cc.o
      ___cxx_global_var_init.3 in model_exporter.cc.o
      ___cxx_global_var_init.49 in constraint_solver.cc.o
      ___cxx_global_var_init.70 in constraint_solver.cc.o
      ...
  "google::FlagRegisterer::FlagRegisterer<long long>(char const*, char const*, char const*, long long*, long long*)", referenced from:
      ___cxx_global_var_init in linear_assignment.cc.o
      ___cxx_global_var_init in min_cost_flow.cc.o
      ___cxx_global_var_init.3 in routing.cc.o
      ___cxx_global_var_init.6 in routing.cc.o
      ___cxx_global_var_init.9 in routing.cc.o
      ___cxx_global_var_init.57 in routing_flags.cc.o
      ___cxx_global_var_init.60 in routing_flags.cc.o
      ...
  "_compress", referenced from:
      recordio::RecordWriter::Compress(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in recordio.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<int>::Pack(operations_research::(anonymous namespace)::addrval<int> const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<long long>::Pack(operations_research::(anonymous namespace)::addrval<long long> const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<unsigned long long>::Pack(operations_research::(anonymous namespace)::addrval<unsigned long long> const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<double>::Pack(operations_research::(anonymous namespace)::addrval<double> const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<void*>::Pack(operations_research::(anonymous namespace)::addrval<void*> const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in constraint_solver.cc.o
     (maybe you meant: __ZNSt3__117__compressed_pairIZN19operations_research3sat17PartialIsOneOfVarE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEERKNS6_INS2_7LiteralENS7_ISC_EEEEEUlPNS2_5ModelEE_NS7_ISJ_EEED2Ev, __ZNSt3__117__compressed_pairIZN19operations_research3sat20ExactlyOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14IsEqualToMinOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat23WeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISF_EEEERKT_xEUlSA_E_NS5_ISN_EEED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat23WeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISF_EEEERKT_xEUlSA_E_NS5_ISN_EELj2EED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat12LiteralXorIsERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEbEUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14IsEqualToMaxOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED2Ev , __ZN19operations_research26ConstraintSolverParameters18set_compress_trailENS_43ConstraintSolverParameters_TrailCompressionE , __ZNSt3__117__compressed_pairIZN19operations_research3sat19AtMostOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat23WeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISF_EEEERKT_xEUlSA_E_NS5_ISN_EEED1Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat30StrictNonOverlappingRectanglesERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEESB_SB_SB_EUlPNS2_5ModelEE_NS7_ISE_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat17PartialIsOneOfVarE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEERKNS6_INS2_7LiteralENS7_ISC_EEEEEUlPNS2_5ModelEE_NS7_ISJ_EEED1Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat30StrictNonOverlappingRectanglesERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEESB_SB_SB_EUlPNS2_5ModelEE_NS7_ISE_EEED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat14IsEqualToMaxOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14IsEqualToMinOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED1Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat20AllDifferentOnBoundsERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED1Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat20AllDifferentOnBoundsERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEEEUlPNS2_5ModelEE_NS7_ISE_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat20AllDifferentOnBoundsERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat34ConditionalWeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEENS2_7LiteralERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISG_EEEERKT_xEUlSA_E_NS5_ISO_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat30StrictNonOverlappingRectanglesERKNS_6vectorI7IntTypeINS2_20IntegerVariable_tag_EiENS_9allocatorIS6_EEEESB_SB_SB_EUlPNS2_5ModelEE_NS7_ISE_EEED1Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat12LiteralXorIsERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEbEUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat16ClauseConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14ReifiedBoolAndERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEES4_EUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14ReifiedBoolAndERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEES4_EUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat16ClauseConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat16ClauseConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat34ConditionalWeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEENS2_7LiteralERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISG_EEEERKT_xEUlSA_E_NS5_ISO_EEED1Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat18NewIntegerVariableERKNS_6vectorINS1_14ClosedIntervalENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat18NewIntegerVariableERKNS_6vectorINS1_14ClosedIntervalENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat14ReifiedBoolAndERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEES4_EUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat14IsEqualToMinOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat20ExactlyOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat19AtMostOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZN3fLB33FLAGS_routing_gzip_compress_trailE , __ZNSt3__117__compressed_pairIZN19operations_research3sat20SubcircuitConstraintERKNS_6vectorINS3_I7IntTypeINS2_17LiteralIndex_tag_EiENS_9allocatorIS6_EEEENS7_IS9_EEEEEUlPNS2_5ModelEE_NS7_ISG_EEED1Ev , __ZN3fLB35FLAGS_norouting_gzip_compress_trailE , __ZNSt3__117__compressed_pairIZN19operations_research3sat12LiteralXorIsERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEbEUlPNS2_5ModelEE_NS5_ISC_EEED1Ev , __ZN3fLB29FLAGS_lp_dump_compressed_fileE , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat20SubcircuitConstraintERKNS_6vectorINS3_I7IntTypeINS2_17LiteralIndex_tag_EiENS_9allocatorIS6_EEEENS7_IS9_EEEEEUlPNS2_5ModelEE_NS7_ISG_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat18NewIntegerVariableERKNS_6vectorINS1_14ClosedIntervalENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EEED2Ev , __ZN3fLB31FLAGS_nolp_dump_compressed_fileE , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat17PartialIsOneOfVarE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEERKNS6_INS2_7LiteralENS7_ISC_EEEEEUlPNS2_5ModelEE_NS7_ISJ_EELj2EED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat20ExactlyOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat19AtMostOneConstraintERKNS_6vectorINS2_7LiteralENS_9allocatorIS4_EEEEEUlPNS2_5ModelEE_NS5_ISC_EELj2EED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat20SubcircuitConstraintERKNS_6vectorINS3_I7IntTypeINS2_17LiteralIndex_tag_EiENS_9allocatorIS6_EEEENS7_IS9_EEEEEUlPNS2_5ModelEE_NS7_ISG_EEED2Ev , __ZNSt3__117__compressed_pairIZN19operations_research3sat14IsEqualToMaxOfE7IntTypeINS2_20IntegerVariable_tag_EiERKNS_6vectorIS5_NS_9allocatorIS5_EEEEEUlPNS2_5ModelEE_NS7_ISE_EEED1Ev , __ZN8recordio12RecordWriter19set_use_compressionEb , __ZNSt3__128__libcpp_compressed_pair_impIZN19operations_research3sat34ConditionalWeightedSumLowerOrEqualINS_6vectorIxNS_9allocatorIxEEEEEENS_8functionIFvPNS2_5ModelEEEENS2_7LiteralERKNS4_I7IntTypeINS2_20IntegerVariable_tag_EiENS5_ISG_EEEERKT_xEUlSA_E_NS5_ISO_EELj2EED2Ev )
  "_compressBound", referenced from:
      operations_research::(anonymous namespace)::ZlibTrailPacker<int>::ZlibTrailPacker(int) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<long long>::ZlibTrailPacker(int) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<unsigned long long>::ZlibTrailPacker(int) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<double>::ZlibTrailPacker(int) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<void*>::ZlibTrailPacker(int) in constraint_solver.cc.o
  "_gzclose", referenced from:
      CoinGzipFileInput::~CoinGzipFileInput() in libCoinUtils.a(CoinFileIO.o)
      CoinGzipFileInput::~CoinGzipFileInput() in libCoinUtils.a(CoinFileIO.o)
      CoinGzipFileOutput::~CoinGzipFileOutput() in libCoinUtils.a(CoinFileIO.o)
  "_gzopen", referenced from:
      CoinGzipFileInput::CoinGzipFileInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libCoinUtils.a(CoinFileIO.o)
      CoinGzipFileOutput::CoinGzipFileOutput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libCoinUtils.a(CoinFileIO.o)
  "_gzread", referenced from:
      CoinGzipFileInput::readRaw(void*, int) in libCoinUtils.a(CoinFileIO.o)
  "_gzwrite", referenced from:
      CoinGzipFileOutput::write(void const*, int) in libCoinUtils.a(CoinFileIO.o)
  "_uncompress", referenced from:
      recordio::RecordReader::Uncompress(char const*, unsigned long long, char*, unsigned long long) const in recordio.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<int>::Unpack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, operations_research::(anonymous namespace)::addrval<int>*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<long long>::Unpack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, operations_research::(anonymous namespace)::addrval<long long>*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<unsigned long long>::Unpack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, operations_research::(anonymous namespace)::addrval<unsigned long long>*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<double>::Unpack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, operations_research::(anonymous namespace)::addrval<double>*) in constraint_solver.cc.o
      operations_research::(anonymous namespace)::ZlibTrailPacker<void*>::Unpack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, operations_research::(anonymous namespace)::addrval<void*>*) in constraint_solver.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libortools.dylib] Error 1
make[1]: *** [CMakeFiles/ortools.dir/all] Error 2
make: *** [all] Error 2
lperron-macbookpro3:build lperron$

**Comment by lperron** [comment]
I cleaned all packages from brew.
Now, it does not build gflags.

I have removed the two QUIET attributes. I do not know why gflags is not even looked for.
Here is the log:

/Applications/CMake.app/Contents/bin/cmake -D CMAKE_INSTALL_PREFIX=/Users/lperron/Work/dist-or-tools ..
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find Protobuf (missing:  Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) (found suitable version "3.3.0", minimum required is "3.3.0")
-- Did not find system protobuf. Building as an external project
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8") 
-- Checking for module 'libglog>=0.3.5'
--   No package 'libglog' found
-- Did not find system glog. Building as an external project.
-- Checking for module 'cbc'
--   No package 'cbc' found
-- Did not find system coin-cbc. Building as an external Project.
-- The C compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lperron/Work/cmake-or-tools/build

**Comment by lperron** [comment]
and I observed that even if the dependency specified cbc 2.9.8, it was happily using cbc 2.9.6 from homebrew.

**Pull request merged**
